### PR TITLE
Changed field name from profile_pic to picture

### PR DESCRIPTION
**Pull request by catoaune**
Got an error using profile_pic "(#100) Tried accessing nonexisting field (profile_pic) on node type (User)" while picture is working

### CODE REVIEW

**Comment by maciekmm** [comment]
@catoaune Thanks for your contribution.

**Comment by maciekmm** [comment]
@catoaune I just tested this because something seemed wrong (the messenger platform documentation mentions profile_pic) and it indeed is profile_pic. I reverted the commit. Could you provide more information of the context of this error?

**Comment by catoaune** [comment]
I am sorry for providing a bad patch. 
I was working on messenger for Workplace by Facebook and got an error when using profile_pic, while picture did work.
I did try to search in the regular Facebook messenger developer documentation to see if profile_pic had been replaced by picture in recent API versions. I found this document - https://developers.facebook.com/docs/graph-api/reference/user - and based on this 
"picture The person's profile picture" 
and the fact that it did work with picture in Workplace, I assumed it had changed also in the regular messenger API. Of course I should not just assume but also test, and I am sorry for that.

**Comment by maciekmm** [comment]
@catoaune No worries :)
Is this library of any help when developing for 'messenger for Workplace'? If so maybe adding a flag to support that product would be a good idea? :>

**Pull request merged**
